# -*- coding: utf-8 -*-
"""songwala01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1abN0x0_dGh8X5y8JVElWlC9gONwfnuhu
"""

import pandas as pd
df = pd.read_csv("/content/sample_data/song_skip_dataset.csv")
print(df.head(20))
print(df.columns)
print(df.describe())

print(df.describe())

print(df.head())
print(df.tail())
print(df.shape)
print(df.columns)
print(df.info())
print(df.describe())
print(df.isnull().sum())
print(df.duplicated().sum())
print(df.nunique())
df.dtypes